### ISSUE TITLE
`com.raizlabs.android.dbflow.kotlinextensions.save` breaks unit tests

### ISSUE THREAD

**Issue by AAverin** [agrosner/DBFlow#1519]
DBFlow Version: 4.2.4

Bug or Feature Request:
After converting to Kotlin classes, I had to import `com.raizlabs.android.dbflow.kotlinextensions.save`, which broke my unit-tests

**Comment by AAverin** [comment]
```
java.lang.IllegalStateException: The global database holder is not initialized. Ensure you call FlowManager.init() before accessing the database.
	at com.raizlabs.android.dbflow.config.FlowManager.checkDatabaseHolder(FlowManager.java:507)
	at com.raizlabs.android.dbflow.config.FlowManager.getDatabaseForTable(FlowManager.java:138)
	at com.raizlabs.android.dbflow.config.FlowManager.getWritableDatabaseForTable(FlowManager.java:165)
```

**Comment by agrosner** [comment]
where are you calling save()? did you initialize db?

**Comment by AyoPrez** [comment]
Same error in Java. Same version.

I initialize the db in the app's application file. It can not be initialized in the unit test file because it needs the context.

**Comment by agrosner** [comment]
kotlin extensions rolled into main lib in 5.0.0-alpha1. closing due to inactivity.
