### ISSUE TITLE
Unable to delete the associated table

### ISSUE THREAD

**Issue by qianshengta** [agrosner/DBFlow#1565]
DBFlow Version:  4.2.4

Bug or Feature Request:Unable to delete the associated table

Description:
```
@Table(database = QianDBFlow.class, name = "AntColony")
public class AntColony extends BaseRXModel implements Serializable {
    @PrimaryKey(autoincrement = true)
    private long colonyId;
    @Column
    private String name;

    @ForeignKey(saveForeignKeyModel = true)
    private AntQueen antQueen;
}
```

```
@Table(database = QianDBFlow.class, name = "AntQueen")
public class AntQueen extends BaseRXModel implements Serializable {

    @PrimaryKey(autoincrement = true)
    private long queenId;
    @Column
    private String name;
}
```
When I delete the AntColony table, it's all right,AntColony has been deleted and AntQueen still exists
```
        RXSQLite.rx(
                SQLite.select().from(AntColony.class))
                .queryList()
                .subscribe(new Consumer<List<AntColony>>() {
                    @Override
                    public void accept(List<AntColony> antColonies) throws Exception {
                        if (!ListUtils.isEmpty(antColonies)) {
                            antColonies.get(0).delete().subscribe(new Consumer<Boolean>() {
                                @Override
                                public void accept(Boolean aBoolean) throws Exception {
                                    select3(true);
                                }
                            });
                        }
                    }
                });
```
But when I delete AntQueen, I will run out
```
        RXSQLite.rx(
                SQLite.select().from(AntQueen.class))
                .queryList()
                .subscribe(new Consumer<List<AntQueen>>() {
                    @Override
                    public void accept(List<AntQueen> antQueens) throws Exception {
                        if (!ListUtils.isEmpty(antQueens)) {
                            antQueens.get(0).delete().subscribe(new Consumer<Boolean>() {
                                @Override
                                public void accept(Boolean aBoolean) throws Exception {
                                    select3(true);
                                }
                            });
                        }
                    }
                });
```
This is my error log
```
 FATAL EXCEPTION: main
                                                                    Process: com.qian.lib.utils, PID: 12786
                                                                    io.reactivex.exceptions.OnErrorNotImplementedException: FOREIGN KEY constraint failed (code 787)
                                                                        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
                                                                        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:48)
                                                                        at io.reactivex.Single.subscribe(Single.java:3220)
                                                                        at io.reactivex.Single.subscribe(Single.java:3206)
                                                                        at io.reactivex.Single.subscribe(Single.java:3177)
                                                                        at com.example.qian.dbflow.DBFlowActivity$10.accept(DBFlowActivity.java:359)
                                                                        at com.example.qian.dbflow.DBFlowActivity$10.accept(DBFlowActivity.java:355)
                                                                        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
                                                                        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
                                                                        at io.reactivex.Single.subscribe(Single.java:3220)
                                                                        at io.reactivex.Single.subscribe(Single.java:3206)
                                                                        at io.reactivex.Single.subscribe(Single.java:3177)
                                                                        at com.example.qian.dbflow.DBFlowActivity.one2one_delete(DBFlowActivity.java:355)
                                                                        at com.example.qian.dbflow.DBFlowActivity.onViewClicked(DBFlowActivity.java:92)
                                                                        at com.example.qian.dbflow.DBFlowActivity_ViewBinding$11.doClick(DBFlowActivity_ViewBinding.java:141)
                                                                        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                        at android.view.View.performClick(View.java:5265)
                                                                        at android.view.View$PerformClick.run(View.java:21527)
                                                                        at android.os.Handler.handleCallback(Handler.java:815)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                        at android.os.Looper.loop(Looper.java:207)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5701)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
```

**Comment by agrosner** [comment]
Use `@Table(deleteForeignKeyModel = true)` so it'll do it automatically. I think you need to delete `AntQueen` first, then `AntColony`. Using `deleteForeignKeyModel` will take care of this for you.
