### ISSUE TITLE
App Crashed when insert multiple values using AsyncTask 

### ISSUE THREAD

**Issue by braver-tool** [agrosner/DBFlow#1687]
# DB-Flow

DBFlow Version:  4.2.4

Bug or Feature Request: Bug

Description:

 Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
        at android.database.CursorWindow.<init>(CursorWindow.java:108)
        at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:140)
        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:134)
        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
        at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:265)
        at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:71)
        at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:21)
        at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:32)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:72)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:60)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)
        at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:36)
        at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:69)
        at com.raizlabs.android.dbflow.sql.language.Where.querySingle(Where.java:249)

**Comment by agrosner** [comment]
related to #1642 #1603 
You may have too many open cursors at once or a Cursor leak somewhere.
